# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f1c7838a625d5f22dce3d1d76db2dab82d8d21e907637d4cd2e083bb0297e3df741155ccd13f70c9f48211d1e8c8fd75e6a7524d4ff1945bdbb977c956ef711

test:
  secret_key_base: d4c13eaa15a05597dd7afe261c26676cd9785f57de4d7078b9db97b7fbb157a41d81540f7dbc59774f1261124ea623496ee3416cfba92b1c7505174838f647f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
